### PR TITLE
Functionality to remove dependencies after gofail disable is run

### PR DESCRIPTION
**Pull request by gap892003**
Needs goImports to be installed

### CODE REVIEW

**Comment by heyitsanthony** [comment]
@gap892003 can you describe what this patch is supposed to fix? The bindings should already be removed on `disable` when the `.fail.go` files are removed (see https://github.com/coreos/gofail/blob/master/gofail.go#L190)

**Comment by gap892003** [comment]
@heyitsanthony this removes any imports that are only specifically used in gofail part of the code. When I ran gofail with package unused in my file it was unable to clear it.

**Comment by gap892003** [comment]
@heyitsanthony sure ! 

`package sompackage

import (
	"fmt"
)

func DoSomething() {
	fmt.Println("returning")
	// gofail: var Startcrash int
	// os.Exit(1)
	// fmt.Println(" it worked !  Crashingggg...",Startcrash)

}
`
for above code after
`gofail enable sompackage/
gofail disable sompackage/`

package os was imported properly(probably IDE handled that) but it was not cleared up.

**Comment by heyitsanthony** [comment]
@gap892003 OK, that seems unreliable if it needs an IDE to restore the import when re-enabling. Doing this kind of pattern with build tags instead might be cleaner:

something.go:
```go
import (
    "fmt"
)

func DoSomething() {
    fmt.Println("returning"
    // gofail: var Startcrash int
    // crash()
}
```

failpoints.go:
```go
// +build failpoint

import "os"

func crash() { os.Exit(1) }
```

**Comment by gap892003** [comment]
@heyitsanthony but what about other packages. Like if I want to use strings.Compare? Do you recommend wiring wrapper functions for those also?  what if we want to use that in multiple packages? We will end up replicating this code in every package? 
(Also If we take out these functions in a separate common package, we would have to import that package)

**Comment by heyitsanthony** [comment]
@gap892003 it would need a separate `// +build failpoint` file for each package using unimported failpoints. Usually a failpoint shouldn't have much code in the first place (e.g., return an error, panic, etc).

Also, another problem with inserting/deleting imports via goimports is the failpoint enabled code won't have the same line numbers as the ordinary code, making backtraces more difficult to read.

**Comment by gap892003** [comment]
@heyitsanthony excellent point! 
And also agree that failpoint shouldn't have much code. But I can easily see use cases where we want to fail based on certain property of the object. Example: You have some instances of cars , and you only want to panic when car's name is "A". Now, if we haven't used strings package in the file, we would   want it to be imported and removed when gofail is enabled. And of course as we discussed taking this function out into another file in same package would quickly become unmanageable.

**Comment by gyuho** [comment]
@gap892003 

As @heyitsanthony said:

> The bindings should already be removed on disable when the .fail.go files are removed

I think `gofail` should not rely on other tools.

Easiest workaround for https://github.com/coreos/gofail/pull/11#issuecomment-381141207, just have an extra line below `// gofail: ` comment, so that `gofail enable` won't edit the `// os.Exit(1)` comment.

**Comment by ahrtr** [comment]
@spzala  we don't need merge this PR based on the discussion. Please close this one. thx

**Comment by spzala** [comment]
@ahrtr thanks for pointing out!

**Pull request closed without merging**
